[package]
name = "kuretiki-chan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai_api_rust = "0.1.8"
serenity = "0.11.5"
